### ISSUE TITLE
سوال در مورد before

### ISSUE THREAD

**Issue by hooman-mirghasemi** [mmonfared/CyBDD#1]
سلام من طبق راهنمایی که کردید توی یوتیوب این کار رو انجام دادم:
```
Before({tags: '@dbfreshdb'}, () => {
  cy.request({
    method: 'GET',
    url: `${Cypress.env("MAIN_API")}/api/test-init-data/fresh-db`,
  });
})
```

یه بیفوری نوشتم با تگ فرش دی بی
و بالا سر فایل قیچرم هم این تگ رو استفاده کردم:
```
@dbfreshdb
Feature: Login features
Scenario: Verify valid login with password
    Then I should not see the "password input"
    ..............
    
    
  Scenario: Verify there is validation on login form
    When I click on "login with password"
    ...........

  Scenario: Verify login with inccorect password is imposible
    When I click on "login with password"
    ......
```

ولی خوب الان این فیچر فایل ۳ تا سناریو تست داره قبل از هر کدوم اونا یکبار این بیفور اجرا میشه در حالی که هدف من اینکه یکبار قبل از اجرای همه تست ها انجام بشه فقط.
میشه راهنمایی کنید که باید چی کار کنم؟

**Comment by mmonfared** [comment]
شما درواقع دنبال BeforeAll هستید که `cypress-cucumber-preprocessor` نداریم. برای رسیدن به این هدف می تونید از هوک before خود سایپرس استفاده کنید و اونو تو فایل e2e قرار بدین تا اگر اسم فیچرفایل ما شامل یه چیز خاصی بود دستورات خاصی اجرا بشن. مثلا فرض کنید اسم این فایل شما `Login.features` هست. ما میخوایم سایپرس قبل از اجرای سناریوهای توی این فایل یه کاری انجام بده. 

`cypress/support/e2e.js[ts]`
```javascript
before(() => {
    const currentFeatureFileName = Cypress.spec.relative;
    if (currentFeatureFileName.includes('Login.feature')) {
      // Code to run once before all tests in Login features
      cy.log('Suite Setup - Executed once before Login features')
    }
  });
```
