### ISSUE TITLE
Changes are not applied when adding another import

### ISSUE THREAD

**Issue by jiridusil** [mmonfared/CyBDD#2]
I'm having issue when adding another import except the cucumber one (Given, When, Then).

This is my step definition file:
```
import {Given, When, Then} from '@badeball/cypress-cucumber-preprocessor';

Given("Test user {word}", (user) => {
    cy.log('Test message')
})
```

I add another import, for example:
import { CreateContractPage } from "../../page/application/create-contract-page.po

 When I change a log message to:
    cy.log('Test message 123')

and re-run the test - cypress shows 'Test message' instead of 'Test message 123'.

Somehow the second import causing issues.

<img width="281" alt="image" src="https://github.com/mmonfared/CyBDD/assets/101554309/bfc16a6a-4984-4a97-9188-b2053ef268d1">

**Comment by mmonfared** [comment]
As I can see `cy.log('Test message 123')` really has nothing to do with your import statements. It is a simple cypress log command. It might be an issue with your IDE or Terminal session where it runs the previous version of the file before updating. Terminate cypress and start it again and retry

**Comment by jiridusil** [comment]
I was able to resolve the issue. The class create-contract-page.po.js was extending another class which has some imports that were invalid. Removing invalid imports from inherited class helped resolve the issue. Thank you for your help.
